name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: list
        run: ls

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - run: npm test
